clmp/contracts/urls.py
from django.urls import include, path, re_path
from . import views

app_name='contracts'

urlpatterns = [
    path('', views.contract_list, name="list"),
    path('create/', views.contract_create, name="create"),
    path('approve/<slug>/', views.contract_approve, name="approve"),
    re_path('(?P<slug>[\w-]+)/', views.contract_detail, name="detail"),
    path('mine_block', views.mine_block, name="mine_block"),
    path('get_chain', views.get_chain, name="get_chain")

]

clmp/contracts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Contract(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    participant = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    contractStatus = models.TextField()

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]

class OfficialIdentity(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    SocialSecurityNumber = models.CharField(max_length=15)
    

clmp/contracts/forms.py
from django import forms
from . import models

class CreateContract(forms.ModelForm):
    class Meta:
        model = models.Contract
        fields = ['title', 'body', 'slug']
        

clmp/contracts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
import json, hashlib, datetime, copy
from django.http import JsonResponse
from django.utils import timezone
from django.http import HttpResponse
from .models import Contract
from . import forms
from . import validate_social_security



def contract_list(request):
    contracts = Contract.objects.all().order_by('date')
    return render(request, 'contracts/contract_list.html', { 'contracts': contracts })

def contract_detail(request, slug):
    # return HttpResponse(slug)
    contract = Contract.objects.get(slug=slug)
    if request.method == 'POST' and str(request.user) not in contract.contractStatus :
        u = User.objects.get(username=request.user)
        if validate_social_security.IsTrue(u.officialidentity.SocialSecurityNumber):
            contract.contractStatus = "Approved by " + str(request.user) + ": " + str(timezone.now())
            contract.save()
            request.session['contract_status'] = str(contract.contractStatus)
            request.session['slug'] = str(slug)
            return redirect('contracts:mine_block')
    return render(request, 'contracts/contract_detail.html', { 'contract': contract })

# add login required here; redirect if not logged in
def contract_create(request):
    if request.method == 'POST':
        form = forms.CreateContract(request.POST)
        if form.is_valid():
            # save contract to the db
            # save it as an instance, don't immediately commit the save
            u = User.objects.get(username=request.user)
            if validate_social_security.IsTrue(u.officialidentity.SocialSecurityNumber):
                instance = form.save(commit=False)
                instance.participant = request.user 
                instance.save()
                return redirect('contracts:list')
    else:
        form = forms.CreateContract()
    return render(request, 'contracts/contract_create.html', {'form': form })

def contract_approve(request, slug):
    contract = Contract.objects.get(slug=slug)
    return render(request, 'contracts/contract_approve.html', {'contract': contract})


class Blockchain:
    def __init__(self):
        self.chain = []
        self.create_block(nonce = 1, previous_hash = '0', slug='', contract_status='')

    def create_block(self, nonce, previous_hash, slug, contract_status):
        block = {'index': len(self.chain) + 1,
                 'timestamp': str(datetime.datetime.now()),
                 'nonce': nonce,
                 'previous_hash': previous_hash,
                 'contract': slug,
                 'contract_status': contract_status}
        self.chain.append(block)
        return block

    def get_previous_block(self):
        return self.chain[-1]

    def proof_of_work(self, previous_nonce):
        new_nonce = 1
        check_nonce = False
        while check_nonce is False:
            hash_operation = hashlib.sha256(str(new_nonce**2 - previous_nonce**2).encode()).hexdigest()
            if hash_operation[:4] == '0000':
                check_nonce = True
            else:
                new_nonce += 1
        return new_nonce

    def hash(self, block):
        encoded_block = json.dumps(block, sort_keys = True).encode()
        return hashlib.sha256(encoded_block).hexdigest()

    def is_chain_valid(self, chain):
        previous_block = chain[0]
        block_index = 1
        while block_index < len(chain):
            block = chain[block_index]
            if block['previous_hash'] != self.hash(previous_block):
                return False
            previous_nonce = previous_block['nonce']
            nonce = block['nonce']
            hash_operation = hashlib.sha256(str(nonce**2 - previous_nonce**2).encode()).hexdigest()
            if hash_operation[:4] != '0000':
                return False
            previous_block = block
            block_index += 1
        return True


# Creating our Blockchain
blockchain = Blockchain()

# Mining a new block
def mine_block(request):
    if request.method == 'GET':
        contract_status = request.session['contract_status']
        slug = request.session['slug']
        previous_block = blockchain.get_previous_block()
        previous_nonce = previous_block['nonce']
        nonce = blockchain.proof_of_work(previous_nonce)
        previous_hash = blockchain.hash(previous_block)
        block = blockchain.create_block(nonce, previous_hash, slug, contract_status)
        response = {'message': 'Congratulations, contract status added to the blockchain!',
                    'index': block['index'],
                    'timestamp': block['timestamp'],
                    'nonce': block['nonce'],
                    'previous_hash': block['previous_hash'],
                    'contract': slug,
                    'contract_status': contract_status}
    return render(request, 'contracts/blockchain.html', {'chain': response })

# Getting the full Blockchain
def get_chain(request):
    if request.method == 'GET':
        response = {'chain': blockchain.chain,
                    'length': len(blockchain.chain)}
    return render(request, 'contracts/blockchain.html', {'chain': response })

# Checking if the Blockchain is valid
def is_valid(request):
    if request.method == 'GET':
        is_valid = blockchain.is_chain_valid(blockchain.chain)
        if is_valid:
            response = {'message': 'All good. The Blockchain is valid.'}
        else:
            response = {'message': 'Houston, we have a problem. The Blockchain is not valid.'}
    return JsonResponse(response)   

clmp/contracts/templates/contracts/blockchain.html
{% extends 'base_layout.html' %} 

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Blockchain</h1>
</div>
<div class="contract-detail">
  {{ chain.message }}
  {% for block in chain.chain %}
  <div class="card contract" style="width: 36rem; margin: 10px 0px 10px 0px;">
    <div class="card-body">
      <h5 class="card-title">Contract: {{ block.contract }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">Status: {{ block.contract_status }}</h6>
      <p class="card-text">previous block hash: {{ block.previous_hash }}</p>
    </div>
  </div>
  {% endfor %}
</div>

<p><a href="{% url 'contracts:list' %}">Go To Contract List</a></p>
{% endblock %}

clmp/contracts/templates/contracts/contract_approve.html
{% extends 'base_layout.html' %} 

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Contract Detail</h1>
</div>
<div class="card contract-approve mx-auto">
    <div class="card-body contract">
      <h5 class="card-title">{{ contract.title }}</h5>
      <p class="card-text">{{ contract.body }}</p>
      <p>contract participant: {{ contract.participant }}</p>
      <p>{{ contract.date }}</p>
      <form class="site-form" action="{% url 'contracts:detail' slug=contract.slug %}" method="post">
          {% csrf_token %}
          <button class="btn btn-success" type="submit">Complete Approval</button>
      </form>
    </div>
  </div>
{% endblock %}

clmp/contracts/templates/contracts/contract_create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Create a New Contract</h1>
</div>
<div class="create-contract">
    <div class="card mx-auto">
        <div class="card-body">
          <h5 class="card-title">Create a New Contract</h5>
          <p class="card-text">Create a new contract by filling in the form fields below.</p>
          <form class="site-form" action="{% url 'contracts:create' %}" method="post">
              {% csrf_token %}
              {{ form }}
          <button class="btn btn-primary" type="submit">Create</button>
        </form>
        </div>
      </div>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

clmp/contracts/templates/contracts/contract_detail.html
{% extends 'base_layout.html' %} 

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Contract Detail</h1>
</div>
<div class="card contract-detail mx-auto">
    <div class="card-body contract">
      <h5 class="card-title">{{ contract.title }}</h5>
      <p class="card-text">{{ contract.body }}</p>
      <p>contract participant: {{ contract.participant }}</p>
      <p>{{ contract.date }}</p>
      <p>{{ contract.contractStatus }}</p>
      {% if contract.contractStatus|length == 0 %}
      <p><a href="{% url 'contracts:approve' slug=contract.slug %}">Go To Contract Approval</a></p>
      {% endif %}
    </div>
  </div>
{% endblock %}

clmp/contracts/templates/contracts/contract_list.html
{% extends 'base_layout.html' %} 

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Contract List</h1>
</div>
  {% for contract in contracts %}
  <div class="card contract" style="width: 36rem; margin: 10px 0px 10px 0px;">
    <div class="card-body">
      <h5 class="card-title"><a href="{% url 'contracts:detail' slug=contract.slug %}">{{ contract.title }}</a></h5>
      <h6 class="card-subtitle mb-2 text-muted">{{ contract.date }}</h6>
      <p class="card-text">contract participant: {{ contract.participant }}</p>
    </div>
  </div>
  {% endfor %}
</div>
<p><a href="{% url 'contracts:get_chain' %}">View Blockchain</a></p>
{% endblock %}